### ISSUE TITLE
Gitea fails to restart on systems with SELinux

### ISSUE THREAD

**Issue by maloo1** [CMiksche/gitea-auto-update#22]
**Describe the bug**
Hi,
On systems running SELinux (Centos in my case) the update fails after the gitea service is restarted.

**To Reproduce**
1. Run gitea-auto-update
2. Restart gitea
3. See the following errors in logs:
gitea.service: Failed to execute command: Permission denied
gitea.service: Failed at step EXEC spawning /usr/local/bin/gitea: Permission denied

**Expected behavior**
gitea starts after upgrade without additional steps/troubleshooting.

**Additional context**
Running restorecon on the file fixes the issue...
[root@git01 ~]# restorecon -v /usr/local/bin/gitea            Relabeled /usr/local/bin/gitea from unconfined_u:object_r:user_tmp_t:s0 to unconfined_u:object_r:bin_t:s0

Alternatively I believe if the file is copied from the tmp folder instead of moved the original context does not remain with the file...

**Comment by CMiksche** [comment]
I don't use a distro with SELinux (I use Arch and SELinux is not officially supported), so help from a developer with SELinux would be nice...

**Comment by maloo1** [comment]
Hi Christof - thanks for the prompt response and putting together this update script!

I've done a little more testing and can confirm that changing the mv to a cp and then cleaninv up in the tmp dir does the trick:

[root@git01 ~]# ls -alZ /usr/local/bin/gitea                  -rwxr-xr-x. 1 root root unconfined_u:object_r:bin_t:s0 115865232 Jun 16 01:45 /usr/local/bin/gitea                          [root@git01 ~]# ls -alZ /tmp/gitea                            -rw-r--r--. 1 root root unconfined_u:object_r:user_tmp_t:s0 115865232 Jun 16 01:37 /tmp/gitea                               [root@git01 ~]# \cp /tmp/gitea /usr/local/bin/gitea           [root@git01 ~]# ls -alZ /usr/local/bin/gitea
-rwxr-xr-x. 1 root root unconfined_u:object_r:bin_t:s0 115865232 Jun 16 01:51 /usr/local/bin/gitea
[root@git01 ~]# \mv /tmp/gitea /usr/local/bin/gitea           [root@git01 ~]# ls -alZ /usr/local/bin/gitea
-rw-r--r--. 1 root root unconfined_u:object_r:user_tmp_t:s0 115865232 Jun 16 01:37 /usr/local/bin/gitea
[root@git01 ~]#

I'll manually change the download.py script on my system and check if it definitely fixes it...

**Comment by CMiksche** [comment]
> I've done a little more testing and can confirm that changing the mv to a cp and then cleaninv up in the tmp dir does the trick

Oh, sounds like a simple fix 👍  

Do you want to create a PR for that or should I commit it?

The `mv` is used in build.py line 19 and download.py line 78 in the lib folder. Sounds like we should replace it with cp and afterwards rm the copied file.
