### ISSUE TITLE
Error updating gitea

### ISSUE THREAD

**Issue by R0GGER** [CMiksche/gitea-auto-update#26]
Current Gitea version: 1.15.10

```
/usr/local/bin/gitea-auto-update --settings=/home/git/update/settings.ini
sha256sum: gitea.xz.sha256: no properly formatted SHA256 checksum lines found
```
How to fix this issue?

**Comment by CMiksche** [comment]
Seems like the Gitea project couldn't upload all files: https://github.com/go-gitea/gitea/releases

They already have a Issue for that: https://github.com/go-gitea/gitea/issues/18474

If you download the source files on your machine, set the dir in the config file (sourceDir=) and set buildFromSource=True, then it can build Gitea locally.

**Comment by CMiksche** [comment]
@R0GGER It seems like the Gitea team has updated the files and I also updated this tool - if there is no sha256 file, it should still work in the future.

Could you try with version 2.0.11 and reopen this issue if the error still occurs?

**Comment by R0GGER** [comment]
@CMiksche 

Yes, solved! Thanks for your quick response.
```
# /usr/local/bin/gitea-auto-update --settings=/home/git/update/settings.ini
update successfully
```
