### ISSUE TITLE
API Access Denied

### ISSUE THREAD

**Issue by johnstonjs** [CMiksche/gitea-auto-update#8]
First, thank you for sharing this script!

I'm unable to get the script working due to API access restrictions.  Looking through [information](https://docs.gitea.io/en-us/api-usage/) on API calls, I've attempted generating access tokens and using them in my Gitea instance URL.  Unfortunately, that doesn't work either, perhaps because I have multi-factor authentication enabled.

If I attempt to access the API version call itself via WGET, I get the following error:
`2019-05-27 17:24:38 ERROR 403: Forbidden.`

When I run `upater.py`, I get the following error:

```
/u/l/b/gitea $ sudo python3 gitea-auto-update/updater.py 
Traceback (most recent call last):
  File "gitea-auto-update/updater.py", line 19, in <module>
    current_version = requests.get(settings.gtsite).json()['version']
KeyError: 'version'
```

Would it be worthwhile to amend the script to simply use the `Gitea` executable for version check?

```
/u/l/b/gitea $ ./gitea -v
Gitea version 1.8.0 built with go1.12.4 : bindata, sqlite, sqlite_unlock_notify
```

**Comment by CMiksche** [comment]
I think using the executable is a good idea for that problem.

This should be handled in a new function which tries to get the version via url first and if that doesn't work, it gets the version via the gitea executable.

**Comment by CMiksche** [comment]
@johnstonjs I've implemented a logic which does frist try to get the version from the gitea file and if that does fail, it will try to get the version via web api.

If you do change the gtsite from the settings.py to a empty string, then the script will get the version from the gitea file.
